#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Base16 Shell
export BASE16_SHELL="$HOME/.config/base16-shell/base16-eighties.dark.sh"
[[ -s $BASE16_SHELL ]] && source $BASE16_SHELL
 
# Customize to your needs...
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000
EDITOR=vim
VISUAL=vim

# Aliases

alias rsync="noglob rsync -azvh"
alias sidebyside="pr -w $COLUMNS -m -t"
alias sbs="sidebyside"
alias tmux="tmux2"
alias tm="agenttmux2 -CC attach"
alias tms="agenttmux2 -CC new -s yelpdev"
alias vf="source $BASE16_SHELL"
alias ack="ag"

#print info about a file
pm() {
    stat -f "%N: %A %Sp %z bytes" $@;
}

#search for a git alias
galias() {
    alias | ag "git .*$@.*";
}

#search for a docker alias
dalias() {
    alias | ag "docker.*$@.*";
}

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
