#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Base16 Shell
BASE16_SHELL="$HOME/.config/base16-shell/base16-eighties.dark.sh"
[[ -s $BASE16_SHELL ]] && source $BASE16_SHELL
 
# Customize to your needs...
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000
EDITOR=vim
VISUAL=vim
DEVBOX=dev11-uswest1cdevc

# Aliases

alias sublime="open -a \"Sublime Text\""
alias rsync="noglob rsync -azvh"
alias sidebyside="pr -w $COLUMNS -m -t"
alias sbs="sidebyside"
alias dev="ssh devbox"
alias mdev="sshfs -p 22 mess@dev11-uswest1cdevc:/nail/home/mess/ ~/Development/devbox -oauto_cache,reconnect,defer_permissions,negative_vncache,volname=devbox"
alias udev="sudo umount -f ~/Development/devbox"
alias tm="tmux -CC attach"
alias tms="tmux -CC new -s yelp"
alias ack="ag"

#print info about a file
pm() {
    stat -f "%N: %A %Sp %z bytes" $@;
}

#search for a git alias
galias() {
    alias | ag "git .*$@.*";
}

#search for a docker alias
dalias() {
    alias | ag "docker.*$@.*";
}

# fasd
eval "$(fasd --init auto)"

# aactivator
eval "$(aactivator init)"

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
